#!/usr/bin/env python3
"""Copy ai8xize synthesis artifacts into indoor_env_1d_e2e and set alpha / CNN input layout.

Example (from repo root):
  python3 misc/retarget_e2e_from_synthesis.py inference/indoor_env_1d_91_q8824
  python3 misc/retarget_e2e_from_synthesis.py inference/indoor_env_1d_51_q8824 --alpha 71
  python3 misc/retarget_e2e_from_synthesis.py inference/indoor_env_1d_91_q8824 --no-export-ctf
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
_E2E_DIR = _REPO_ROOT / "inference" / "indoor_env_1d_e2e"
_SYNTH_COPY = (
    "cnn.c",
    "cnn.h",
    "weights.h",
    "sampledata.h",
    "sampleoutput.h",
    "softmax.c",
    "log.txt",
)


def _parse_load_input(main_c: str) -> tuple[int, int, int, int]:
    """Return (addr_ch0, addr_ch1, words_per_ch, alpha_from_chw_comment)."""
    m0 = re.search(
        r"memcpy32\s*\(\s*\(uint32_t\s*\*\)\s*(0x[0-9a-fA-F]+)\s*,\s*input_0\s*,\s*(\d+)\s*\)",
        main_c,
    )
    m1 = re.search(
        r"memcpy32\s*\(\s*\(uint32_t\s*\*\)\s*(0x[0-9a-fA-F]+)\s*,\s*input_8\s*,\s*(\d+)\s*\)",
        main_c,
    )
    if not m0 or not m1:
        raise ValueError("Could not find load_input() memcpy32 lines in synthesis main.c")
    addr0 = int(m0.group(1), 16)
    words = int(m0.group(2))
    addr1 = int(m1.group(1), 16)
    if int(m1.group(2)) != words:
        raise ValueError("Channel 0/1 word counts differ in load_input()")

    chw = re.search(r"CHW\s+(\d+)x1", main_c)
    alpha_chw = int(chw.group(1)) if chw else 0
    return addr0, addr1, words, alpha_chw


def _parse_alpha_from_artifacts(synth_dir: Path) -> int:
    log_path = synth_dir / "log.txt"
    if log_path.is_file():
        log = log_path.read_text(encoding="utf-8", errors="replace")
        m = re.search(r"Input dimensions\s*=\s*\[\[(\d+),\s*1\]", log)
        if m:
            return int(m.group(1))

    cnn_path = synth_dir / "cnn.c"
    if cnn_path.is_file():
        cnn = cnn_path.read_text(encoding="utf-8", errors="replace")
        m = re.search(r"Layer 0:\s*2x(\d+),", cnn)
        if m:
            return int(m.group(1))

    return 0


def _parse_sampledata_words(synth_dir: Path) -> int:
    sample_path = synth_dir / "sampledata.h"
    if not sample_path.is_file():
        return 0

    sample = sample_path.read_text(encoding="utf-8", errors="replace")
    counts = []
    for name in ("SAMPLE_INPUT_0", "SAMPLE_INPUT_8"):
        m = re.search(rf"#define\s+{name}\s+\{{(.*?)\n\}}", sample, flags=re.S)
        if not m:
            return 0
        counts.append(len(re.findall(r"0x[0-9a-fA-F]+", m.group(1))))

    if counts[0] != counts[1]:
        raise ValueError("Channel 0/1 word counts differ in sampledata.h")
    return counts[0]


def _write_preprocess_config(
    path: Path,
    synth_name: str,
    alpha: int,
    addr0: int,
    addr1: int,
    words: int,
) -> None:
    text = f"""// Auto-generated by misc/retarget_e2e_from_synthesis.py — do not edit by hand
#ifndef PREPROCESS_CONFIG_H
#define PREPROCESS_CONFIG_H

#define E2E_SYNTH_SOURCE "{synth_name}"
#define CTF_ALPHA {alpha}
#define CNN_INPUT_ADDR_CH0 ((uint32_t)0x{addr0:08X})
#define CNN_INPUT_ADDR_CH1 ((uint32_t)0x{addr1:08X})
#define CNN_INPUT_WORDS_PER_CH {words}

#endif // PREPROCESS_CONFIG_H
"""
    path.write_text(text, encoding="utf-8")


def _export_ctf(alpha: int) -> None:
    export_py = _REPO_ROOT / "misc" / "export_ctf_raw_h.py"
    venv_py = _REPO_ROOT / "misc" / ".venv" / "bin" / "python"
    py = str(venv_py) if venv_py.is_file() else sys.executable
    subprocess.run(
        [py, str(export_py), "--alpha", str(alpha)],
        cwd=_REPO_DIR if (_REPO_DIR := _REPO_ROOT) else None,
        check=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "synthesis_dir",
        type=Path,
        help="Synthesized project dir, e.g. inference/indoor_env_1d_91_q8824",
    )
    parser.add_argument(
        "--alpha",
        type=int,
        default=None,
        help="CTF length (default: parse CHW Nx1 from synthesis main.c)",
    )
    parser.add_argument(
        "--no-export-ctf",
        action="store_true",
        help="Skip regenerating ctf_recordings.h (requires scipy)",
    )
    args = parser.parse_args()

    synth_dir = args.synthesis_dir
    if not synth_dir.is_absolute():
        synth_dir = (_REPO_ROOT / synth_dir).resolve()
    if not synth_dir.is_dir():
        print(f"error: not a directory: {synth_dir}", file=sys.stderr)
        return 1

    main_c_path = synth_dir / "main.c"
    if not main_c_path.is_file():
        print(f"error: missing {main_c_path}", file=sys.stderr)
        return 1

    main_c = main_c_path.read_text(encoding="utf-8")
    addr0, addr1, main_words, alpha_chw = _parse_load_input(main_c)
    alpha_artifact = _parse_alpha_from_artifacts(synth_dir)
    sample_words = _parse_sampledata_words(synth_dir)

    alpha = args.alpha if args.alpha is not None else (alpha_artifact or alpha_chw)
    if alpha <= 0 or alpha > 101:
        print(
            f"error: invalid alpha={alpha} (use --alpha or fix CHW comment in {main_c_path})",
            file=sys.stderr,
        )
        return 1
    words = sample_words or main_words

    synth_name = synth_dir.name
    print(f"Retargeting e2e -> {synth_name}  (alpha={alpha}, words/ch={words})")
    if alpha_chw and alpha_chw != alpha:
        print(
            f"note: synthesis main.c CHW says alpha={alpha_chw}, but generated artifacts say alpha={alpha}; "
            "using generated artifacts"
        )
    if sample_words and main_words != sample_words:
        print(
            f"note: synthesis main.c load_input says words/ch={main_words}, but sampledata.h has "
            f"words/ch={sample_words}; using sampledata.h"
        )

    for name in _SYNTH_COPY:
        src = synth_dir / name
        if not src.is_file():
            print(f"warning: skip missing {src}", file=sys.stderr)
            continue
        shutil.copy2(src, _E2E_DIR / name)

    _write_preprocess_config(
        _E2E_DIR / "preprocess_config.h",
        synth_name,
        alpha,
        addr0,
        addr1,
        words,
    )
    print(f"Wrote {_E2E_DIR / 'preprocess_config.h'}")

    if not args.no_export_ctf:
        try:
            _export_ctf(alpha)
        except (subprocess.CalledProcessError, FileNotFoundError) as exc:
            print(f"warning: ctf export failed ({exc}); run export_ctf_raw_h.py --alpha {alpha}", file=sys.stderr)
    else:
        print("Skipped ctf_recordings.h (re-run export_ctf_raw_h.py with matching --alpha)")

    wait_mode = "__NOP" if alpha <= 71 else "sleep"
    print(f"CNN wait default for alpha={alpha}: {wait_mode} (<=71 uses __NOP; override -DE2E_CNN_WAIT_NOP)")

    print("\nNext:")
    print("  cd inference/indoor_env_1d_e2e && make -r -j 8 TARGET=MAX78002 BOARD=EvKit_V1")
    print("  Optional: E2E_RUN_KAT=0 in project.mk if KAT does not match your ctf recording")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
