/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// indoor_env_1d_101
// This file was @generated by ai8xize.py --test-dir ../ai8x-training/ai8x_seed_runs_out/HW_Evaluation/ --prefix indoor_env_1d_101 --checkpoint-file ../ai8x-training/ai8x_seed_runs_out/HW_Evaluation/indoor_mixed_seed_46__L101__8_8_8_8_indoor_mixed_seed_46__L101__8_8_8_8_qat_best_q8.pth.tar --config-file networks/indoorenvnet-v2-chw-101.yaml --sample-input tests/sample_indoorenvironment_1d_101.npy --device MAX78002 --timer 0 --display-checkpoint --verbose --overwrite --softmax --compact-data --mexpress

#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
#include "mxc.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"

volatile uint32_t cnn_time; // Stopwatch
#define NUM_RUNS 10000
#define PRINT_EVERY 100
static uint32_t t_us[NUM_RUNS]; // Per-run latencies (us)

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// 2-channel 101x1 data input (202 bytes total / 101 bytes per channel):
// CHW 101x1, channel 0
static const uint32_t input_0[] = SAMPLE_INPUT_0;

// CHW 101x1, channel 1
static const uint32_t input_8[] = SAMPLE_INPUT_8;

void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  memcpy32((uint32_t *) 0x51800000, input_0, 26);
  memcpy32((uint32_t *) 0x51840000, input_8, 26);
}

// Expected output of layer 3 for indoor_env_1d_101 given the sample input (known-answer test)
// Delete this function for production code
static const uint32_t sample_output[] = SAMPLE_OUTPUT;
int check_output(void)
{
  int i;
  uint32_t mask, len;
  volatile uint32_t *addr;
  const uint32_t *ptr = sample_output;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    mask = *ptr++;
    len = *ptr++;
    for (i = 0; i < len; i++)
      if ((*addr++ & mask) != *ptr++) {
        printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
               i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
        return CNN_FAIL;
      }
  }

  return CNN_OK;
}

// Classification layer:
static int32_t ml_data[CNN_NUM_OUTPUTS];
static q15_t ml_softmax[CNN_NUM_OUTPUTS];

void softmax_layer(void)
{
  cnn_unload((uint32_t *) ml_data);
  softmax_q17p14_q15((const q31_t *) ml_data, CNN_NUM_OUTPUTS, ml_softmax);
}

int main(void)
{
  int i;
  int digs, tens;
  uint64_t sum_inf_us = 0;
  double sum_sq = 0.0;

  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 120 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  MXC_GCR->ipll_ctrl |= MXC_F_GCR_IPLL_CTRL_EN; // Enable IPLL
  SystemCoreClockUpdate();

  printf("Waiting...\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed

  // Enable peripheral, enable CNN interrupt, turn on CNN clock
  // CNN clock: PLL (200 MHz) div 4
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV4);

  printf("\n*** CNN Inference Test indoor_env_1d_101 ***\n");

  cnn_init(); // Bring state machine into consistent state
  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine

  printf("*** %d runs (run 1 & every %d) ***\n", NUM_RUNS, PRINT_EVERY);

  // Inference loop
  for (i = 0; i < NUM_RUNS; i++) {
    load_input(); // Load data input

    // Fast CNN clock for inference: PLL (200 MHz) div 1
    MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                       | MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1 | MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL;

    cnn_time = 0;
    cnn_start(); // Start CNN processing

    // Busy-wait to keep SWD responsive (avoid sleep-related hangs)
    while (cnn_time == 0) { __NOP(); }

    // Slow down clock for printing/aggregation
    MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                       | MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV4 | MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL;

    t_us[i] = cnn_time;
    sum_inf_us += cnn_time;
    sum_sq += (double)cnn_time * (double)cnn_time;

    if (i == 0 || ((i + 1) % PRINT_EVERY) == 0) {
      printf("Run %4d latency: %u us\n", i + 1, t_us[i]);
    }
  }

  // Verify & softmax on last output
  if (check_output() != CNN_OK) fail();
  softmax_layer();
  printf("\n*** PASS ***\n\n");

  // Stats
  {
    double mean = (double)sum_inf_us / (double)NUM_RUNS;
    double std = sqrt(sum_sq / (double)NUM_RUNS - mean * mean);
    printf("Inference total time: %llu us (avg %.4f us/run)\n",
           (unsigned long long)sum_inf_us, mean);
    printf("\nLatency over %d runs:\n  Mean: %.4f us\n  Std-dev: %.4f us\n  Last: %.3f us\n",
           NUM_RUNS, mean, std, (double)t_us[NUM_RUNS - 1]);
  }

  // Classification results (last run)
  printf("\nClassification results:\n");
  for (i = 0; i < CNN_NUM_OUTPUTS; i++) {
    digs = (1000 * ml_softmax[i] + 0x4000) >> 15;
    tens = digs % 10;
    digs = digs / 10;
    printf("[%7d] -> Class %d: %d.%d%%\n", ml_data[i], i, digs, tens);
  }

  cnn_disable(); // Shut down CNN clock, disable peripheral

  MXC_GCR->ipll_ctrl &= ~MXC_F_GCR_IPLL_CTRL_EN; // Disable IPLL

  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 241,380 ops (239,160 macc; 2,220 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 7,070 ops (6,060 macc; 1,010 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 31,310 ops (30,300 macc; 1,010 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 202,200 ops (202,000 macc; 200 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 800 ops (800 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 203,160 bytes out of 2,396,160 bytes total (8.5%)
  Bias memory:   224 bytes out of 8,192 bytes total (2.7%)
*/

