/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// indoor_env
// This file was @generated by ai8xize.py --test-dir ../indoor_env --prefix indoor_env --checkpoint-file ../ai8x-training/logs/indoor_run_87___2025.07.13-202612/indoor_run_87_qat_best_q8.pth.tar --config-file networks/indoorenvnet-v1-hwc.yaml --sample-input tests/sample_indoorenvironment.npy --device MAX78002 --timer 0 --display-checkpoint --verbose --overwrite --softmax --compact-data --mexpress


// indoor_env – multi‑run timing version (prints run 1 & every 100th run, 3 decimals)

#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <math.h>              // sqrt()
#include "mxc.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"

/* ---------- user‑adjustable parameters ---------- */
#define NUM_RUNS     1000      // total inferences
#define PRINT_EVERY  100       // print on runs 1,100,200,…

/* ---------- globals ---------- */
volatile uint32_t cnn_time;                // stopwatch (set in CNN ISR)
static uint32_t   t_us[NUM_RUNS];          // raw timings
static int32_t    ml_data[CNN_NUM_OUTPUTS];
static q15_t      ml_softmax[CNN_NUM_OUTPUTS];

/* ---------- helpers ---------- */
void fail(void)
{
    printf("\n*** FAIL ***\n\n");
    while (1);
}

/* 1‑channel 101x2 sample (202 bytes / 51 words) */
static const uint32_t input_0[] = SAMPLE_INPUT_0;

void load_input(void)
{
    memcpy32((uint32_t *)0x51800000, input_0, 202);
}

/* Known‑answer test */
// Expected output of layer 3 for indoor_env given the sample input (known-answer test)
// Delete this function for production code
static const uint32_t sample_output[] = SAMPLE_OUTPUT;
int check_output(void)
{
  int i;
  uint32_t mask, len;
  volatile uint32_t *addr;
  const uint32_t *ptr = sample_output;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    mask = *ptr++;
    len = *ptr++;
    for (i = 0; i < len; i++)
      if ((*addr++ & mask) != *ptr++) {
        printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
               i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
        return CNN_FAIL;
      }
  }

  return CNN_OK;
}

void softmax_layer(void)
{
    cnn_unload((uint32_t *)ml_data);
    softmax_q17p14_q15((const q31_t *)ml_data, CNN_NUM_OUTPUTS, ml_softmax);
}

/* ------------------------------------------------------------------------- */
int main(void)
{
    int i;
    double sum = 0.0, sum_sq = 0.0;

    /* ---------- system clocks / cache ---------- */
    MXC_ICC_Enable(MXC_ICC0);
    MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
    MXC_GCR->ipll_ctrl |= MXC_F_GCR_IPLL_CTRL_EN;   // enable 200 MHz PLL
    SystemCoreClockUpdate();

    printf("Waiting...\n");
    MXC_Delay(SEC(2));                 // let debugger attach

    /* ---------- enable CNN peripheral once ---------- */
    cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL,
               MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV4);

    cnn_init();            // reset state machine
    cnn_load_weights();    // load kernels (once)
    cnn_load_bias();
    cnn_configure();       // set up layers

    printf("\n*** CNN Inference Test indoor_env ***\n");
    printf("\n*** %d runs (print run 1 & every %d) ***\n",
           NUM_RUNS, PRINT_EVERY);

    /* ---------- main timing loop ---------- */
    for (i = 0; i < NUM_RUNS; ++i) {
        load_input();                      // (same sample each time)

        /* fast clock: PLL /1 for inference */
        MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv &
                           ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV |
                             MXC_F_GCR_PCLKDIV_CNNCLKSEL)) |
                           MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1 |
                           MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL;

        cnn_time = 0;
        cnn_start();

        while (cnn_time == 0)
            MXC_LP_EnterSleepMode();       // wait for ISR

        t_us[i] = cnn_time;
        sum    += cnn_time;
        sum_sq += (double)cnn_time * cnn_time;

        /* slow clock back to PLL /4 for UART safety */
        MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv &
                           ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV |
                             MXC_F_GCR_PCLKDIV_CNNCLKSEL)) |
                           MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV4 |
                           MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL;

        /* -------------- progress print -------------- */
        if (i == 0 || ((i + 1) % PRINT_EVERY) == 0) {
            printf("Run %4d latency: %.3f µs\n",
                   i + 1, (double)t_us[i]);
        }
    }

    /* ---------- optional correctness check ---------- */
    if (check_output() != CNN_OK) fail();
    softmax_layer();

    /* ---------- stats ---------- */
    double mean = sum / NUM_RUNS;
    double var  = (sum_sq / NUM_RUNS) - (mean * mean);
    double std  = sqrt(var);

    printf("\nLatency over %d runs (µs):\n", NUM_RUNS);
    printf("  Mean   : %.3f\n", mean);
    printf("  Std‑dev: %.3f\n", std);
    printf("  Last   : %.3f\n", (double)t_us[NUM_RUNS - 1]);

    /* ---------- classification results (last run) ---------- */
    printf("\nClassification results (last run):\n");
    for (i = 0; i < CNN_NUM_OUTPUTS; i++) {
        int digs = (1000 * ml_softmax[i] + 0x4000) >> 15;
        printf("[%7d] -> Class %d: %d.%d%%\n",
               ml_data[i], i, digs / 10, digs % 10);
    }

    /* ---------- cleanup ---------- */
    cnn_disable();
    MXC_GCR->ipll_ctrl &= ~MXC_F_GCR_IPLL_CTRL_EN;

    printf("\n*** DONE ***\n");
    return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 107,310 ops (105,240 macc; 2,070 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 10,100 ops (9,090 macc; 1,010 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 46,460 ops (45,450 macc; 1,010 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 50,550 ops (50,500 macc; 50 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 200 ops (200 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 50,970 bytes out of 2,396,160 bytes total (2.1%)
  Bias memory:   64 bytes out of 8,192 bytes total (0.8%)
*/

