/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// indoor_env_1d_71
// This file was @generated by ai8xize.py --test-dir ../ai8x-training/ai8x_seed_runs_out/HW_Evaluation/ --prefix indoor_env_1d_71 --checkpoint-file ../ai8x-training/ai8x_seed_runs_out/HW_Evaluation/indoor_mixed_seed_46__L71__8_8_8_8_indoor_mixed_seed_46__L71__8_8_8_8_qat_best_q8.pth.tar --config-file networks/indoorenvnet-v2-chw-71.yaml --sample-input tests/sample_indoorenvironment_1d_71.npy --device MAX78002 --timer 0 --display-checkpoint --verbose --overwrite --softmax --compact-data --mexpress --energy

#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"

mxc_gpio_cfg_t gpio_trig1, gpio_trig2; // Port pins for PMON
volatile uint32_t cnn_time; // Stopwatch

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// 2-channel 71x1 data input (142 bytes total / 71 bytes per channel):
// CHW 71x1, channel 0
static const uint32_t input_0[] = SAMPLE_INPUT_0;

// CHW 71x1, channel 1
static const uint32_t input_8[] = SAMPLE_INPUT_8;

void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  memcpy32((uint32_t *) 0x51800000, input_0, 18);
  memcpy32((uint32_t *) 0x51840000, input_8, 18);
}

// Expected output of layer 3 for indoor_env_1d_71 given the sample input (known-answer test)
// Delete this function for production code
static const uint32_t sample_output[] = SAMPLE_OUTPUT;
int check_output(void)
{
  int i;
  uint32_t mask, len;
  volatile uint32_t *addr;
  const uint32_t *ptr = sample_output;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    mask = *ptr++;
    len = *ptr++;
    for (i = 0; i < len; i++)
      if ((*addr++ & mask) != *ptr++) {
        printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
               i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
        return CNN_FAIL;
      }
  }

  return CNN_OK;
}

// Classification layer:
static int32_t ml_data[CNN_NUM_OUTPUTS];
static q15_t ml_softmax[CNN_NUM_OUTPUTS];

void softmax_layer(void)
{
  cnn_unload((uint32_t *) ml_data);
  softmax_q17p14_q15((const q31_t *) ml_data, CNN_NUM_OUTPUTS, ml_softmax);
}

int main(void)
{
  int i;
  int digs, tens;

  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 120 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  MXC_GCR->ipll_ctrl |= MXC_F_GCR_IPLL_CTRL_EN; // Enable IPLL
  SystemCoreClockUpdate();

  printf("Waiting...\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed

  // Configure port pins for PMON
  gpio_trig1.port = MXC_GPIO1;
  gpio_trig1.mask = MXC_GPIO_PIN_6;
  gpio_trig1.pad = MXC_GPIO_PAD_NONE;
  gpio_trig1.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_trig1);

  gpio_trig2.port = MXC_GPIO1;
  gpio_trig2.mask = MXC_GPIO_PIN_7;
  gpio_trig2.pad = MXC_GPIO_PAD_NONE;
  gpio_trig2.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_trig2);

  cnn_disable(); // Disable clock and power to CNN
  // Enable primary clock
  MXC_SYS_ClockSourceEnable(MXC_SYS_CLOCK_IPO);

  printf("Measuring system base (idle) power...\n");
  SYS_START;
  MXC_Delay(SEC(1));
  SYS_COMPLETE;

  // Enable peripheral, enable CNN interrupt, turn on CNN clock
  // CNN clock: PLL (200 MHz) div 4
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV4);

  printf("\n*** CNN Inference Test indoor_env_1d_71 ***\n");

  cnn_init(); // Bring state machine into consistent state

  printf("Measuring weight loading...\n");
  CNN_START;
  for (i = 0; i < 100; i++)
    cnn_load_weights(); // Load kernels
  CNN_COMPLETE;

  MXC_TMR_Delay(MXC_TMR0, 500000);
  printf("Measuring input loading...\n");
  CNN_START;
  for (i = 0; i < 100; i++)
    load_input(); // Load data input
  CNN_COMPLETE;

  cnn_load_bias();
  cnn_configure(); // Configure state machine

  MXC_TMR_Delay(MXC_TMR0, 500000);
  printf("Measuring input load + inference...\n");
  CNN_START; // Allow capture of processing time
  for (i = 0; i < 100; i++) {
    load_input(); // Load data input
    // CNN clock: PLL (200 MHz) div 1
    MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                       | MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1 | MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL;
    cnn_start(); // Run inference
    // Busy-wait to keep SWD responsive (avoid sleep-related hangs)
    while (cnn_time == 0) { __NOP(); }
    // CNN clock: PLL (200 MHz) div 4
    MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                       | MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV4 | MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL;
  }
  CNN_COMPLETE;

  // Switch CNN clock to PLL (200 MHz) div 4

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV4 | MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL;
  if (check_output() != CNN_OK) fail();
  softmax_layer();

  printf("\n*** PASS ***\n\n");

#ifdef CNN_INFERENCE_TIMER
  printf("Approximate inference time: %u us\n\n", cnn_time);
#endif

  printf("See monitor display for inference energy.\n\n");

  cnn_disable(); // Shut down CNN clock, disable peripheral

  MXC_GCR->ipll_ctrl &= ~MXC_F_GCR_IPLL_CTRL_EN; // Disable IPLL

  printf("Classification results:\n");
  for (i = 0; i < CNN_NUM_OUTPUTS; i++) {
    digs = (1000 * ml_softmax[i] + 0x4000) >> 15;
    tens = digs % 10;
    digs = digs / 10;
    printf("[%7d] -> Class %d: %d.%d%%\n", ml_data[i], i, digs, tens);
  }

  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 169,980 ops (168,360 macc; 1,620 comp; 0 add; 0 mul; 0 bitwise)
    Layer 0: 4,970 ops (4,260 macc; 710 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1: 22,010 ops (21,300 macc; 710 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2: 142,200 ops (142,000 macc; 200 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3: 800 ops (800 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 143,160 bytes out of 2,396,160 bytes total (6.0%)
  Bias memory:   224 bytes out of 8,192 bytes total (2.7%)
*/

