/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// indoor_env_1d_101_q8824
// This file was @generated by /Users/hamza/Desktop/testMax/ai8x-synthesis/ai8xize.py --test-dir /Users/hamza/Desktop/testMax/ai8x-training/ai8x_seed_runs_out/HW_Evaluation --prefix indoor_env_1d_101_q8824 --checkpoint-file /Users/hamza/Desktop/testMax/ai8x-training/ai8x_seed_runs_out/HW_Evaluation/FINAL/indoor_mixed_seed_46__L101__8_8_2_4_indoor_mixed_seed_46__L101__8_8_2_4_qat_best_qmixed.pth.tar --config-file /Users/hamza/Desktop/testMax/ai8x-synthesis/networks/indoorenvnet-v2-chw-101.yaml --sample-input /Users/hamza/Desktop/testMax/ai8x-synthesis/tests/sample_indoorenvironment_1d_101.npy --device MAX78002 --timer 0 --display-checkpoint --verbose --overwrite --softmax --compact-data --mexpress --energy

// DO NOT EDIT - regenerate this file instead!

// Configuring 4 layers
// Input data: CHW
// Layer 0: 2x101, no pooling, conv1d with kernel size 3, stride 1, pad 1, ReLU, 10x101 output
// Layer 1: 10x101, no pooling, conv1d with kernel size 3, stride 1, pad 1, ReLU, 10x101 output
// Layer 2: 10x101x1 flattened to 1010x1x1, no pooling, linear, ReLU, 200x1x1 output
// Layer 3: 200x1x1, no pooling, linear, no activation, 4x1x1 output

// Final Scales: {0: 0, 1: 0, 2: 0, 3: 4}

#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

void CNN_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x51000000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x52000000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x53000000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x54000000) &= ~((1<<12) | 1);

#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x51000000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x51000000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0)
      *addr++ = *ptr++;
  }

  return CNN_OK;
}

static const uint8_t bias_0[] = BIAS_0;
static const uint8_t bias_1[] = BIAS_1;
static const uint8_t bias_2[] = BIAS_2;
static const uint8_t bias_3[] = BIAS_3;

static void memcpy_8to32(uint32_t *dst, const uint8_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

int cnn_load_bias(void)
{
  memcpy_8to32((uint32_t *) 0x51180000, bias_0, sizeof(uint8_t) * 200);
  memcpy_8to32((uint32_t *) 0x52180000, bias_1, sizeof(uint8_t) * 10);
  memcpy_8to32((uint32_t *) 0x53180000, bias_2, sizeof(uint8_t) * 10);
  memcpy_8to32((uint32_t *) 0x54180000, bias_3, sizeof(uint8_t) * 4);

  return CNN_OK;
}

int cnn_init(void)
{
  *((volatile uint32_t *) 0x51000000) = 0x00000008; // Enable clocks
  *((volatile uint32_t *) 0x52000000) = 0x00000008; // Enable clocks
  *((volatile uint32_t *) 0x53000000) = 0x00000008; // Enable clocks
  *((volatile uint32_t *) 0x54000000) = 0x00000008; // Enable clocks
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x51000004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x52000004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x53000004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x54000004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x5100000c) = 0x00001c80; // Clear registers
  *((volatile uint32_t *) 0x5200000c) = 0x00001c80; // Clear registers
  *((volatile uint32_t *) 0x5300000c) = 0x00001c80; // Clear registers
  *((volatile uint32_t *) 0x5400000c) = 0x00001c80; // Clear registers
  while ((*((volatile uint32_t *) 0x5100000c) & 0x2000000) != 0x2000000); // Wait for clear
  while ((*((volatile uint32_t *) 0x5200000c) & 0x2000000) != 0x2000000); // Wait for clear
  while ((*((volatile uint32_t *) 0x5300000c) & 0x2000000) != 0x2000000); // Wait for clear
  while ((*((volatile uint32_t *) 0x5400000c) & 0x2000000) != 0x2000000); // Wait for clear
  *((volatile uint32_t *) 0x5100000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5200000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5300000c) = 0x00000000; // Reset BIST
  *((volatile uint32_t *) 0x5400000c) = 0x00000000; // Reset BIST

  *((volatile uint32_t *) 0x51000000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x51000008) = 0x00000003; // Layer count
  *((volatile uint32_t *) 0x52000000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x52000008) = 0x00000003; // Layer count
  *((volatile uint32_t *) 0x53000000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x53000008) = 0x00000003; // Layer count
  *((volatile uint32_t *) 0x54000000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x54000008) = 0x00000003; // Layer count

  return CNN_OK;
}

int cnn_configure(void)
{
  // Layer 0 quadrant 0
  *((volatile uint32_t *) 0x51100004) = 0x00018064; // Rows
  *((volatile uint32_t *) 0x51100008) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x51100018) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x5110001c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x51100024) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x51100030) = 0x00802b60; // Layer control
  *((volatile uint32_t *) 0x51100034) = 0x00048000; // Layer control 2
  *((volatile uint32_t *) 0x51100038) = 0x00000048; // Mask count
  *((volatile uint32_t *) 0x51100040) = 0x00000009; // Output channel count
  *((volatile uint32_t *) 0x5110000c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x5110004c) = 0x00008000; // Post processing register
  *((volatile uint32_t *) 0x51100048) = 0x01010101; // Mask and processor enables

  // Layer 0 quadrant 1
  *((volatile uint32_t *) 0x52100004) = 0x00018064; // Rows
  *((volatile uint32_t *) 0x52100008) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x52100018) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x5210001c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x52100024) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x52100030) = 0x00800b60; // Layer control
  *((volatile uint32_t *) 0x52100034) = 0x00048000; // Layer control 2
  *((volatile uint32_t *) 0x52100038) = 0x00000048; // Mask count
  *((volatile uint32_t *) 0x52100040) = 0x00000009; // Output channel count
  *((volatile uint32_t *) 0x5210000c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x5210004c) = 0x00009000; // Post processing register

  // Layer 0 quadrant 2
  *((volatile uint32_t *) 0x53100004) = 0x00018064; // Rows
  *((volatile uint32_t *) 0x53100008) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x53100018) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x5310001c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x53100024) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x53100030) = 0x00800b60; // Layer control
  *((volatile uint32_t *) 0x53100034) = 0x00048000; // Layer control 2
  *((volatile uint32_t *) 0x53100038) = 0x00000048; // Mask count
  *((volatile uint32_t *) 0x53100040) = 0x00000009; // Output channel count
  *((volatile uint32_t *) 0x5310000c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x5310004c) = 0x00008000; // Post processing register

  // Layer 0 quadrant 3
  *((volatile uint32_t *) 0x54100004) = 0x00018064; // Rows
  *((volatile uint32_t *) 0x54100008) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x54100018) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x5410001c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x54100024) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x54100030) = 0x00800b60; // Layer control
  *((volatile uint32_t *) 0x54100034) = 0x00048000; // Layer control 2
  *((volatile uint32_t *) 0x54100038) = 0x00000048; // Mask count
  *((volatile uint32_t *) 0x54100040) = 0x00000009; // Output channel count
  *((volatile uint32_t *) 0x5410000c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x5410004c) = 0x00008000; // Post processing register

  // Layer 1 quadrant 0
  *((volatile uint32_t *) 0x51100104) = 0x00018064; // Rows
  *((volatile uint32_t *) 0x51100108) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x51100118) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x51100124) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5110012c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x51100130) = 0x00804b20; // Layer control
  *((volatile uint32_t *) 0x51100134) = 0x00048000; // Layer control 2
  *((volatile uint32_t *) 0x51100138) = 0x000000a8; // Mask count
  *((volatile uint32_t *) 0x5110013c) = 0x00000060; // Mask offset
  *((volatile uint32_t *) 0x51100140) = 0x00000009; // Output channel count
  *((volatile uint32_t *) 0x5110010c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x51100148) = 0x03ff03ff; // Mask and processor enables

  // Layer 1 quadrant 1
  *((volatile uint32_t *) 0x52100104) = 0x00018064; // Rows
  *((volatile uint32_t *) 0x52100108) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x52100118) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x52100124) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5210012c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x52100130) = 0x00800b20; // Layer control
  *((volatile uint32_t *) 0x52100134) = 0x00048000; // Layer control 2
  *((volatile uint32_t *) 0x52100138) = 0x000000a8; // Mask count
  *((volatile uint32_t *) 0x5210013c) = 0x00000060; // Mask offset
  *((volatile uint32_t *) 0x52100140) = 0x00000009; // Output channel count
  *((volatile uint32_t *) 0x5210010c) = 0x00001300; // 1D

  // Layer 1 quadrant 2
  *((volatile uint32_t *) 0x53100104) = 0x00018064; // Rows
  *((volatile uint32_t *) 0x53100108) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x53100118) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x53100124) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5310012c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x53100130) = 0x00800b20; // Layer control
  *((volatile uint32_t *) 0x53100134) = 0x00048000; // Layer control 2
  *((volatile uint32_t *) 0x53100138) = 0x000000a8; // Mask count
  *((volatile uint32_t *) 0x5310013c) = 0x00000060; // Mask offset
  *((volatile uint32_t *) 0x53100140) = 0x00000009; // Output channel count
  *((volatile uint32_t *) 0x5310010c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x5310014c) = 0x00001000; // Post processing register

  // Layer 1 quadrant 3
  *((volatile uint32_t *) 0x54100104) = 0x00018064; // Rows
  *((volatile uint32_t *) 0x54100108) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x54100118) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x54100124) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5410012c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x54100130) = 0x00800b20; // Layer control
  *((volatile uint32_t *) 0x54100134) = 0x00048000; // Layer control 2
  *((volatile uint32_t *) 0x54100138) = 0x000000a8; // Mask count
  *((volatile uint32_t *) 0x5410013c) = 0x00000060; // Mask offset
  *((volatile uint32_t *) 0x54100140) = 0x00000009; // Output channel count
  *((volatile uint32_t *) 0x5410010c) = 0x00001300; // 1D

  // Layer 2 quadrant 0
  *((volatile uint32_t *) 0x51100204) = 0x00010000; // Rows
  *((volatile uint32_t *) 0x51100208) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x51100218) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x5110021c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x51100220) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x51100224) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x51100228) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x51100230) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x51100234) = 0x00066034; // Layer control 2
  *((volatile uint32_t *) 0x51100238) = 0x0000a00e; // Mask count
  *((volatile uint32_t *) 0x5110023c) = 0x00000240; // Mask offset
  *((volatile uint32_t *) 0x51100240) = 0x00004ee7; // Output channel count
  *((volatile uint32_t *) 0x5110020c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x51100244) = 0x006400c9; // TRAM ptr max
  *((volatile uint32_t *) 0x5110024c) = 0x08983000; // Post processing register
  *((volatile uint32_t *) 0x51100248) = 0x03ff03ff; // Mask and processor enables

  // Layer 2 quadrant 1
  *((volatile uint32_t *) 0x52100204) = 0x00010000; // Rows
  *((volatile uint32_t *) 0x52100208) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x52100218) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x5210021c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x52100220) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x52100224) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x52100228) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x52100230) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x52100234) = 0x00066034; // Layer control 2
  *((volatile uint32_t *) 0x52100238) = 0x0000a00e; // Mask count
  *((volatile uint32_t *) 0x5210023c) = 0x00000240; // Mask offset
  *((volatile uint32_t *) 0x52100240) = 0x00004ee7; // Output channel count
  *((volatile uint32_t *) 0x5210020c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x52100244) = 0x006400c9; // TRAM ptr max
  *((volatile uint32_t *) 0x5210024c) = 0x08982000; // Post processing register

  // Layer 2 quadrant 2
  *((volatile uint32_t *) 0x53100204) = 0x00010000; // Rows
  *((volatile uint32_t *) 0x53100208) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x53100218) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x5310021c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x53100220) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x53100224) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x53100228) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x53100230) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x53100234) = 0x00066034; // Layer control 2
  *((volatile uint32_t *) 0x53100238) = 0x0000a00e; // Mask count
  *((volatile uint32_t *) 0x5310023c) = 0x00000240; // Mask offset
  *((volatile uint32_t *) 0x53100240) = 0x00004ee7; // Output channel count
  *((volatile uint32_t *) 0x5310020c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x53100244) = 0x006400c9; // TRAM ptr max
  *((volatile uint32_t *) 0x5310024c) = 0x08982000; // Post processing register

  // Layer 2 quadrant 3
  *((volatile uint32_t *) 0x54100204) = 0x00010000; // Rows
  *((volatile uint32_t *) 0x54100208) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x54100218) = 0x00000010; // Stride
  *((volatile uint32_t *) 0x5410021c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x54100220) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x54100224) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x54100228) = 0x00000001; // Write ptr multi-pass channel offs
  *((volatile uint32_t *) 0x54100230) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x54100234) = 0x00066034; // Layer control 2
  *((volatile uint32_t *) 0x54100238) = 0x0000a00e; // Mask count
  *((volatile uint32_t *) 0x5410023c) = 0x00000240; // Mask offset
  *((volatile uint32_t *) 0x54100240) = 0x00004ee7; // Output channel count
  *((volatile uint32_t *) 0x5410020c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x54100244) = 0x006400c9; // TRAM ptr max
  *((volatile uint32_t *) 0x5410024c) = 0x08982000; // Post processing register

  // Layer 3 quadrant 0
  *((volatile uint32_t *) 0x51100304) = 0x00040000; // Rows
  *((volatile uint32_t *) 0x51100308) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x51100318) = 0x00000040; // Stride
  *((volatile uint32_t *) 0x51100320) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x51100324) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5110032c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x51100330) = 0x0001e920; // Layer control
  *((volatile uint32_t *) 0x51100334) = 0x0000c003; // Layer control 2
  *((volatile uint32_t *) 0x51100338) = 0x0000a11c; // Mask count
  *((volatile uint32_t *) 0x5110033c) = 0x0000a0e0; // Mask offset
  *((volatile uint32_t *) 0x51100340) = 0x0000000f; // Output channel count
  *((volatile uint32_t *) 0x5110030c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x5110034c) = 0x00c22000; // Post processing register
  *((volatile uint32_t *) 0x51100348) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 1
  *((volatile uint32_t *) 0x52100304) = 0x00040000; // Rows
  *((volatile uint32_t *) 0x52100308) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x52100318) = 0x00000040; // Stride
  *((volatile uint32_t *) 0x52100320) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x52100324) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5210032c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x52100330) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x52100334) = 0x0000c003; // Layer control 2
  *((volatile uint32_t *) 0x52100338) = 0x0000a11c; // Mask count
  *((volatile uint32_t *) 0x5210033c) = 0x0000a0e0; // Mask offset
  *((volatile uint32_t *) 0x52100340) = 0x0000000f; // Output channel count
  *((volatile uint32_t *) 0x5210030c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x5210034c) = 0x00c22000; // Post processing register
  *((volatile uint32_t *) 0x52100348) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 2
  *((volatile uint32_t *) 0x53100304) = 0x00040000; // Rows
  *((volatile uint32_t *) 0x53100308) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x53100318) = 0x00000040; // Stride
  *((volatile uint32_t *) 0x53100320) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x53100324) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5310032c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x53100330) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x53100334) = 0x0000c003; // Layer control 2
  *((volatile uint32_t *) 0x53100338) = 0x0000a11c; // Mask count
  *((volatile uint32_t *) 0x5310033c) = 0x0000a0e0; // Mask offset
  *((volatile uint32_t *) 0x53100340) = 0x0000000f; // Output channel count
  *((volatile uint32_t *) 0x5310030c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x5310034c) = 0x00c22000; // Post processing register
  *((volatile uint32_t *) 0x53100348) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 3
  *((volatile uint32_t *) 0x54100304) = 0x00040000; // Rows
  *((volatile uint32_t *) 0x54100308) = 0x00010000; // Columns
  *((volatile uint32_t *) 0x54100318) = 0x00000040; // Stride
  *((volatile uint32_t *) 0x54100320) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x54100324) = 0x00008000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5410032c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x54100330) = 0x00010920; // Layer control
  *((volatile uint32_t *) 0x54100334) = 0x0000c003; // Layer control 2
  *((volatile uint32_t *) 0x54100338) = 0x0000a11c; // Mask count
  *((volatile uint32_t *) 0x5410033c) = 0x0000a0e0; // Mask offset
  *((volatile uint32_t *) 0x54100340) = 0x0000000f; // Output channel count
  *((volatile uint32_t *) 0x5410030c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x5410034c) = 0x00c23000; // Post processing register
  *((volatile uint32_t *) 0x54100348) = 0x000f000f; // Mask and processor enables


  return CNN_OK;
}

int cnn_start(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x51000000) = 0x00100808; // Enable quadrant 0
  *((volatile uint32_t *) 0x52000000) = 0x00100809; // Enable quadrant 1
  *((volatile uint32_t *) 0x53000000) = 0x00100809; // Enable quadrant 2
  *((volatile uint32_t *) 0x54000000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

  *((volatile uint32_t *) 0x51000000) = 0x00100009; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_unload(uint32_t *out_buf)
{
  volatile uint32_t *addr;

  // Custom unload for this network, layer 3: 32-bit data, shape: (4, 1, 1)
  addr = (volatile uint32_t *) 0x51800000;
  *out_buf++ = (*addr++) << 4;
  *out_buf++ = (*addr++) << 4;
  *out_buf++ = (*addr++) << 4;
  *out_buf++ = (*addr++) << 4;

  return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
  // Reset all domains, restore power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_Delay(MSEC(10)); // Wait for load switches
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  if (clock_source == MXC_S_GCR_PCLKDIV_CNNCLKSEL_IPLL)
    while ((MXC_GCR->ipll_ctrl & MXC_F_GCR_IPLL_CTRL_RDY) != MXC_F_GCR_IPLL_CTRL_RDY) ; // Wait for PLL

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

  return CNN_OK;
}

int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}

